### ISSUE TITLE
[TODO] Paperplane Extended's Wishlist

### ISSUE THREAD

**Issue by AvinashReddy3108** [AvinashReddy3108/PaperplaneExtended#27]
### Here's what I would like to add/change in the future of Paperplane Extended.

- [x] Make BOTLOG_CHATID not compulsory for notes, filters, snips, welcomes which involve only text.
- [ ] Better Termux Compatibility (Something like a LITE mode, since termux can't install some packages like Google Chrome and Selenium.)

- [ ] Improve and or rewrite the CMD_HELP part, to make much moar sense and avoid HUGE help texts.
- [ ] Better formatting for text for many cases (Italics for memes, Mono for info/errors, etc, leaving Plain Text for stuff actually typed by the user.)

Anything else, let me know about it in the Issues section.

**Comment by smyaknti** [comment]
Full on heroku dyno restart support (using heroku API) and also auto restart whole dyno if telethon gives the memes.

Came to know that if the auto reconnect flag is disabled then telethon will throw an error and stop. We can capture that and give a full dyno restart command.
